#python intvos_model_triplet.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --RESULT_ROOT ../../result/result_total_local12_100000 --SAVE_RESULT_DIR /data01/jiaxu/saved_model/triplet_test
#CUDA_VISIBLE_DEVICES=6 python inter_net.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --SAVE_RESULT_DIR /data01/jiaxu/saved_model/total_re_inter_new --SAVE_VOS_RESULT_DIR /data01/jiaxu/saved_model/saved_model_total_re_  --MODEL_USEIntSeg False
#CUDA_VISIBLE_DEVICES=5 python inttest_localmemory_fast.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_inter_new_noaspp --RESULT_ROOT ../../result/inter_result_saved_model_inter_new_noaspp_ceshi --MODEL_USEIntSeg True --TEST_MODE True
#CUDA_VISIBLE_DEVICES=7 python inttest_localmemory_fast.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_total_re_inter --RESULT_ROOT ../../result/inter_result_saved_model_inter_re_480_854_2_ --MODEL_USEIntSeg False --TEST_MODE True
CUDA_VISIBLE_DEVICES=6 python inttest_pre.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --SAVE_RESULT_DIR /data01/jiaxu/saved_model/total_re_inter_new --RESULT_ROOT ../../result/ab/inter_result_total_newtest --MODEL_USEIntSeg False --TEST_MODE True
#CUDA_VISIBLE_DEVICES=7 python inttest_localmemory_fast.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --SAVE_RESULT_DIR /data01/jiaxu/saved_model/total_re_inter_nnnnn --RESULT_ROOT ../../result/inter_result_total_re_inter_nnnnn_1 --MODEL_USEIntSeg False --TEST_MODE True




#CUDA_VISIBLE_DEVICES=7 python intvos_model_new.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --RESULT_ROOT ../../result/saved_model_total_rere --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_total_rere   --MODEL_MAX_LOCAL_DISTANCE 12
#CUDA_VISIBLE_DEVICES=7 python intvos_model_localrefine.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --RESULT_ROOT ../../result/result_localrefine_ --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_local_refine --MODEL_SIAMESE_ATTETION False
#CUDA_VISIBLE_DEVICES=2 python inter_net.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --SAVE_RESULT_DIR /data01/jiaxu/saved_model/total_re_inter --SAVE_VOS_RESULT_DIR /data01/jiaxu/saved_model/total_re
#CUDA_VISIBLE_DEVICES=1 python inttest_localmemory_fast.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_edge_inter_1 --RESULT_ROOT ../../result/inter_result_saved_model_edge_inter_1_re
#CUDA_VISIBLE_DEVICES=7 python intvos_model_preround.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --RESULT_ROOT ../../result/result_preround_nomap --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_preround_nomap_1 --MODEL_SIAMESE_ATTETION False --MODEL_PREROUND_MAP False
#CUDA_VISIBLE_DEVICES=3 python intvos_model_tem.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --RESULT_ROOT ../../result/result_templete_select_head_0.9 --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_templete_select_head_0.9 --MODEL_SIAMESE_ATTETION False --MODEL_MAX_LOCAL_DISTANCE 12  --MODEL_SELECT_PERCENT 0.9
#CUDA_VISIBLE_DEVICES=0 python intvos_model_sel.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --RESULT_ROOT ../../result/result_total_re_sel_0.7 --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_total_re_ --MODEL_SIAMESE_ATTETION False --MODEL_MAX_LOCAL_DISTANCE 12 --MODEL_SELECT_PERCENT 0.7
#CUDA_VISIBLE_DEVICES=6 python intvos_model_edge.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --RESULT_ROOT ../../result/saved_model_bceedge_useedge_lr0005  --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_bceedge_useedge_lr0005 --MODEL_SIAMESE_ATTETION False --MODEL_MAX_LOCAL_DISTANCE 12 --MODEL_USE_EDGE True
#CUDA_VISIBLE_DEVICES=1 python inter_net_edge.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_bceedge_inter_useedge_expand3/ --SAVE_VOS_RESULT_DIR /data01/jiaxu/saved_model/saved_model_total_re_  --MODEL_USE_EDGE True --MODEL_USE_EDGE_2 False --MODEL_USE_EDGE_3 False
#CUDA_VISIBLE_DEVICES=0 python inttest_edge.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_inter_edge_NNNNN --RESULT_ROOT ../../result/saved_model_inter_edge_NNNNN --MODEL_USE_EDGE True --MODEL_USE_EDGE_2 False --MODEL_USE_EDGE_3 False --USE2ROUND 2  --USE1DIST 15
#CUDA_VISIBLE_DEVICES=3 python inttest_center.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --SAVE_RESULT_DIR /data01/jiaxu/saved_model/saved_model_inter_center_new_True_True_False --RESULT_ROOT ../../result/saved_model_bceedge_inter_ --CENTER_CAT True   --FUSE True --USE_PRE False

#CUDA_VISIBLE_DEVICES=4 python inter_net_new.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --SAVE_RESULT_DIR /data01/jiaxu/saved_model/total_re_inter --SAVE_VOS_RESULT_DIR /data01/jiaxu/saved_model/saved_model_total_re_
#CUDA_VISIBLE_DEVICES=5 python inter_net_center.py --DATA_ROOT ~/jiaxu_2/data/DAVIS --PRETRAINED_MODEL ~/jiaxu/model_best.pth.tar --SAVE_RESULT_DIR /data01/jiaxu/saved_model/total_re_inter_center --SAVE_VOS_RESULT_DIR /data01/jiaxu/saved_model/saved_model_total_re_ --CENTER_CAT True   --FUSE True --USE_PRE True
